apiVersion: apps/v1
kind: Deployment
metadata:
  name: jikji-ai
  namespace: jikji-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jikji-ai
  template:
    metadata:
      labels:
        app: jikji-ai
    spec:
      containers:
        - name: jikji-ai
          image: ghcr.io/n3n-dev/jikji-ai:latest
          ports:
            - containerPort: 3000
